worker_processes 1;

events {
    worker_connections 1024;
}

http {
    limit_req_zone $binary_remote_addr zone=perip:10m rate=10r/s;
    limit_conn_zone $binary_remote_addr zone=addr:10m;
    log_format main "$remote_addr";
    include conf.d/*.conf;
}
